[build]
  # أمر البناء
  command = "npm run build"
  
  # مجلد الإخراج
  publish = "dist"
  
  # متغيرات البيئة
  environment = { NODE_VERSION = "18" }

# إعدادات المعالجة - دع Vite يتولى التحسين
[build.processing]
  skip_processing = false

# إعادة توجيه للتطبيقات أحادية الصفحة (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# رؤوس الأمان
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# رؤوس التخزين المؤقت للأصول الثابتة
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# رؤوس للخطوط
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
